[workspace]
members  = ["crates/*"]
resolver = "3"

[workspace.package]
authors      = ["Reverier-Xu <reverier.xu@woooo.tech>"]
edition      = "2024"
homepage     = "https://design.woooo.tech/"
license      = "MIT"
publish      = true
repository   = "https://github.com/Reverier-Xu/woocraft"
rust-version = "1.93.0"
version      = "0.1.0"

[profile.release]
codegen-units = 1
lto           = "thin"
opt-level     = 3
panic         = "abort"
strip         = true

[workspace.dependencies]
anyhow      = "1.0"
gpui        = "0.2"
gpui-macros = "0.2"
thiserror   = "2.0"
