use std::{collections::BTreeSet, env, fs, io::Write, path::PathBuf};

const BUILTIN_ASSET_PREFIX: &str = "tech.woooo.woocraft/assets";

fn main() {
  let icons_dir = PathBuf::from("src/assets/icons");
  println!("cargo::rerun-if-changed={}", icons_dir.display());

  let mut entries = Vec::new();
  let mut seen_variants = BTreeSet::new();

  for entry in fs::read_dir(&icons_dir).expect("failed to read src/assets/icons") {
    let entry = entry.expect("failed to read icon dir entry");
    let path = entry.path();
    if !path.is_file() {
      continue;
    }

    if path.extension().and_then(|ext| ext.to_str()) != Some("svg") {
      continue;
    }

    println!("cargo::rerun-if-changed={}", path.display());

    let stem = path
      .file_stem()
      .and_then(|s| s.to_str())
      .expect("invalid utf-8 icon file name");

    let variant = to_variant_name(stem);
    if !seen_variants.insert(variant.clone()) {
      panic!("duplicated icon enum variant generated: {variant}");
    }

    let file_name = path
      .file_name()
      .and_then(|s| s.to_str())
      .expect("invalid utf-8 icon file name")
      .to_owned();

    entries.push((variant, format!("{BUILTIN_ASSET_PREFIX}/icons/{file_name}")));
  }

  entries.sort_by(|a, b| a.0.cmp(&b.0));

  let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set"));
  let generated = out_dir.join("icon_names.rs");
  let mut file = fs::File::create(&generated).expect("failed to create generated icon file");

  write_generated_file(&mut file, &entries).expect("failed to write generated icon file");
}

fn to_variant_name(stem: &str) -> String {
  let mut name = String::new();

  for part in stem
    .split(|c: char| !c.is_ascii_alphanumeric())
    .filter(|p| !p.is_empty())
  {
    let mut chars = part.chars();
    if let Some(first) = chars.next() {
      if first.is_ascii_alphabetic() {
        name.push(first.to_ascii_uppercase());
      } else {
        name.push(first);
      }

      for ch in chars {
        if ch.is_ascii_alphabetic() {
          name.push(ch.to_ascii_lowercase());
        } else {
          name.push(ch);
        }
      }
    }
  }

  if name.is_empty() {
    panic!("could not generate icon enum variant from file name: {stem}");
  }

  if name.chars().next().is_some_and(|c| c.is_ascii_digit()) {
    format!("Icon{name}")
  } else {
    name
  }
}

fn write_generated_file(out: &mut fs::File, entries: &[(String, String)]) -> std::io::Result<()> {
  writeln!(out, "// @generated by crates/woocraft/build.rs")?;
  writeln!(
    out,
    "#[derive(IntoElement, Clone, Copy, Debug, Eq, PartialEq, Hash)]"
  )?;
  writeln!(out, "pub enum IconName {{")?;
  for (variant, _) in entries {
    writeln!(out, "    {variant},")?;
  }
  writeln!(out, "}}")?;
  writeln!(out)?;

  writeln!(out, "pub const ALL_ICON_NAMES: &[IconName] = &[")?;
  for (variant, _) in entries {
    writeln!(out, "    IconName::{variant},")?;
  }
  writeln!(out, "];")?;
  writeln!(out)?;

  writeln!(out, "impl IconName {{")?;
  writeln!(out, "    pub fn all() -> &'static [IconName] {{")?;
  writeln!(out, "        ALL_ICON_NAMES")?;
  writeln!(out, "    }}")?;
  writeln!(out, "}}")?;
  writeln!(out)?;

  writeln!(out, "impl IconNamed for IconName {{")?;
  writeln!(out, "    fn path(self) -> SharedString {{")?;
  writeln!(out, "        match self {{")?;
  for (variant, path) in entries {
    writeln!(out, "            Self::{variant} => \"{path}\",")?;
  }
  writeln!(out, "        }}")?;
  writeln!(out, "        .into()")?;
  writeln!(out, "    }}")?;
  writeln!(out, "}}")?;

  Ok(())
}
