[package]
build       = "build.rs"
description = "GPUI components lib for Woocraft design system."
name        = "woocraft"

authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
publish      = { workspace = true }
readme       = { workspace = true }
repository   = { workspace = true }
rust-version = { workspace = true }
version      = { workspace = true }

[dependencies]
gpui               = { workspace = true }
gpui-base          = { workspace = true }
gpui-platform      = { workspace = true }
palette            = { workspace = true }
rust-i18n          = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
thiserror          = { workspace = true }
toml               = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }

crossbeam-channel = { workspace = true, optional = true }
rust-embed        = { workspace = true, optional = true }
zstd              = { workspace = true, optional = true }

[features]
default = ["resources"]
resources = ["dep:rust-embed", "dep:zstd"]
tray = [
  "dep:crossbeam-channel",
  "dep:image",
  "dep:objc2",
  "dep:objc2-app-kit",
  "dep:objc2-foundation",
  "dep:windows",
  "dep:zbus",
]

[target.'cfg(target_os = "linux")'.dependencies]
zbus = { workspace = true, optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
objc2            = { workspace = true, optional = true }
objc2-app-kit    = { workspace = true, optional = true }
objc2-foundation = { workspace = true, optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, optional = true }

[target.'cfg(any(target_os = "linux", target_os = "windows"))'.dependencies]
image = { workspace = true, optional = true }

[dev-dependencies]
gpui-platform = { workspace = true }

[[example]]
name              = "window_tray"
required-features = ["tray"]

[lints]
workspace = true
