[package]
description = "GPUI components lib for Woocraft design system."
name        = "woocraft"
build       = "build.rs"

authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }
rust-version = { workspace = true }
version      = { workspace = true }

[dependencies]
anyhow      = { workspace = true }
gpui        = { workspace = true }
gpui-macros = { workspace = true }
palette     = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
thiserror   = { workspace = true }
toml        = { workspace = true }

# For assets embedding, optional and workspace to avoid unnecessary dependency for users who don't need it.
rust-embed = { workspace = true, optional = true }
rust-i18n = { workspace = true }

[features]
default   = ["resources"]
resources = ["dep:rust-embed"]
